config_version = "0"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[plugins.definitions.actionlint]
config_files = ["actionlint.yaml"]
exported_config_paths = ["actionlint.yaml"]

[plugins.definitions.actionlint.drivers.lint]
script = "actionlint -config-file ${config_file} -format \"{{json .}}\" ${target}"
