config_version = "0"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[plugins.definitions.actionlint]
config_files = ["actionlint.yaml"]
exported_config_paths = ["actionlint.yaml"]
