config_version = "0"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"
config_files = ["actionlint.yaml"]

[plugins.definitions.actionlint]
exported_config_paths = ["actionlint.yaml"]
